/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Chunks1024 {
  chunk: string;
  created_at: Generated<Timestamp>;
  embeddings: string;
  id: Generated<string>;
  metadata: Json | null;
  model: string;
  source_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface GooseDbVersion {
  id: Generated<number>;
  is_applied: boolean;
  tstamp: Generated<Timestamp | null>;
  version_id: Int8;
}

export interface Notes {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Sources {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  source: string;
}

export interface DB {
  chunks_1024: Chunks1024;
  goose_db_version: GooseDbVersion;
  notes: Notes;
  sources: Sources;
}
